name: taxonlfq
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - jupyter
  - scipy
  - numba
  - streamlit
  - biopython
  - pyahocorasick
  - pip
